# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adddress_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adddress_line_2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adddress_type',
            new_name='address_type',
        ),
    ]
