# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190131_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='suburb',
            field=models.CharField(default='Fourways', max_length=120),
        ),
    ]
